/*
 * World Monthly Temperatures — map front-end.
 *
 * Plain ES2020 in one file, no build step: index.html is meant to be opened
 * straight from disk (file://). MapLibre GL JS v5 is the only external code and
 * is loaded from unpkg by index.html.
 *
 * Data comes from data/cities.js (generated by the scraper) when that file
 * exists, otherwise from mock/mock-cities.js, so the UI always has something to
 * draw. See getCityList().
 */

// OpenFreeMap `liberty` — a colourful OSM style, no API key required.
// Alternatives: bright (more vivid), positron (muted grey).
const MAP_STYLE_URL = 'https://tiles.openfreemap.org/styles/liberty';

// The style JSON (and its source metadata) is cached in localStorage for a day,
// mirroring the server's own max-age, so reloads only re-fetch what the browser
// has not cached. Versioned: bump to invalidate.
const STYLE_CACHE_KEY = 'world-temperature-map.style.v1';
const STYLE_CACHE_MS = 24 * 60 * 60 * 1000;

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];
const MONTH_SHORT = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

// The three selectable metrics: toggle label -> field of city.months.
const METRICS = [
  { id: 'high', label: 'High', row: 'meanDailyMax' },
  { id: 'average', label: 'Average', row: 'dailyMean' },
  { id: 'low', label: 'Low', row: 'meanDailyMin' },
];
const DEFAULT_METRIC_ID = 'average';

// Badge colours come straight from Wikipedia's {{Weather box}} temperature ramp
// (Module:Weather box/colors#_temperature_color): deep blue at -42.75 °C, white
// at +4.5 °C, red at +41.5 °C. See colorForTemperature().
const NO_DATA_COLOR = '#c9ced6';
const LIGHT_TEXT_COLOR = '#ffffff';
const DARK_TEXT_COLOR = '#000000';

// Legend ticks, labelled in °C.
const LEGEND_TICKS = [-25, -10, 0, 10, 20, 30, 40];

const PLAY_INTERVAL_MS = 1500;

const MINUS_SIGN = '\u2212'; // real minus for popup figures; badges use ASCII '-'
const EM_DASH = '\u2014';
const NORTH_EAST_ARROW = '\u2197';
const DEGREE_C = '\u00b0C';

const DATA_SOURCE_ID = 'cities';
const CIRCLE_LAYER_ID = 'city-badges';
const CLUSTER_CIRCLE_LAYER_ID = 'city-cluster-badges';
const LABEL_LAYER_ID = 'city-badge-labels';
const CLUSTER_LABEL_LAYER_ID = 'city-cluster-labels';

// Reference parallels: the equator and both tropics, at the current mean
// obliquity (23.4367°, drifting by about 0.000013°/year). Each line spans the
// full longitude range, so MapLibre repeats it on every world copy.
const REFERENCE_LINE_SOURCE_ID = 'reference-parallels';
const REFERENCE_LINE_LAYER_ID = 'reference-parallel-dashes';
const REFERENCE_LABEL_LAYER_ID = 'reference-parallel-labels';
const REFERENCE_PARALLELS = [
  { name: 'EQUATOR', latitude: 0 },
  { name: 'TROPIC OF CANCER', latitude: 23.4367 },
  { name: 'TROPIC OF CAPRICORN', latitude: -23.4367 },
];

// Overlapping badges merge into clusters up to this zoom level; beyond it every
// city is drawn individually.
const CLUSTER_MAX_ZOOM = 7;
const CLUSTER_RADIUS = 46;

/* --------------------------------------------------------------------------
 * Pure helpers
 * ------------------------------------------------------------------------ */

// data/cities.js wins when it loaded; mock/mock-cities.js is the fallback.
function getCityList() {
  const source = typeof CITY_DATA !== 'undefined' ? CITY_DATA : MOCK_CITY_DATA;
  const list = Array.isArray(source) ? source : (source && Array.isArray(source.cities) ? source.cities : []);
  return list.filter(isPlottableCity);
}

function isPlottableCity(city) {
  return Boolean(city) && Number.isFinite(Number(city.lat)) && Number.isFinite(Number(city.lon));
}

// Number for the given month/metric, or null when the row or the month is blank.
function monthValue(city, monthIndex, metricRow) {
  const series = city && city.months ? city.months[metricRow] : null;
  const value = Array.isArray(series) ? series[monthIndex] : null;
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

// Port of Module:Weather box/colors `range_pos`: 0 at `start`, 1 at `stop`.
function rangePosition(value, start, stop) {
  if (start < stop) {
    if (value < start) return 0;
    if (value > stop) return 1;
    return (value - start) / (stop - start);
  }
  if (value < stop) return 1;
  if (value > start) return 0;
  return (start - value) / (start - stop);
}

// The Lua module formats each 0..255 channel with %02X, which truncates.
function colorByte(value) {
  const clamped = Math.min(255, Math.max(0, Math.floor(value)));
  return clamped.toString(16).padStart(2, '0');
}

// Exact port of Wikipedia's `_temperature_color` (Module:Weather box/colors):
// R and G ramp from 0 at -42.75 °C to 255 at +4.5 °C; above 4.5 °C R stays 255
// while G falls to 0 at +41.5 °C and B reaches 0 at +23 °C.
function colorForTemperature(celsius) {
  const red = celsius < 4.5
    ? 255 * rangePosition(celsius, -42.75, 4.5)
    : 255 * rangePosition(celsius, 60, 41.5);
  const green = celsius <= 4.5
    ? 255 * rangePosition(celsius, -42.75, 4.5)
    : 255 * rangePosition(celsius, 41.5, 4.5);
  const blue = celsius < -42.78
    ? 255 * rangePosition(celsius, -90, -42.78)
    : 255 * rangePosition(celsius, 23, 4.5);
  return `#${colorByte(red)}${colorByte(green)}${colorByte(blue)}`;
}

// MapLibre expression version of the same ramp, sampled every 2.5 °C, for
// cluster colours (clusters are computed inside MapLibre, not in JS).
function temperatureColorExpression(valueExpression) {
  const stops = [];
  for (let celsius = -45; celsius <= 45; celsius += 2.5) {
    stops.push(celsius, colorForTemperature(celsius));
  }
  return ['interpolate', ['linear'], valueExpression, ...stops];
}

function legendTickPosition(celsius) {
  const first = LEGEND_TICKS[0];
  const last = LEGEND_TICKS[LEGEND_TICKS.length - 1];
  return ((celsius - first) / (last - first)) * 100;
}

function readCachedStyle() {
  try {
    const entry = JSON.parse(localStorage.getItem(STYLE_CACHE_KEY) || 'null');
    if (!entry || !entry.style || entry.expires < Date.now()) return null;
    const { style } = entry;
    return style.version === 8 && style.sources ? style : null;
  } catch {
    return null; // storage blocked or corrupted entry
  }
}

function writeCachedStyle(style) {
  try {
    localStorage.setItem(STYLE_CACHE_KEY, JSON.stringify({ expires: Date.now() + STYLE_CACHE_MS, style }));
  } catch {
    // storage disabled or full: the map still works, just without the shortcut
  }
}

// Hands MapLibre a style object from cache, or fetches and caches it first.
// Falls back to letting MapLibre fetch the URL itself if anything goes wrong.
async function applyMapStyle(map) {
  const cached = readCachedStyle();
  if (cached) {
    map.setStyle(cached);
    return;
  }
  try {
    const response = await fetch(MAP_STYLE_URL);
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const style = await response.json();
    if (!style || style.version !== 8 || !style.sources) throw new Error('unexpected style document');
    writeCachedStyle(style);
    map.setStyle(style);
  } catch (error) {
    console.warn('[temperature-map] style fetch failed, loading by URL instead:', error.message);
    map.setStyle(MAP_STYLE_URL);
  }
}

// Sampled every 5 °C from colorForTemperature, so the gradient matches the
// badges (and therefore Wikipedia) as closely as CSS allows.
function legendGradientCss() {
  const first = LEGEND_TICKS[0];
  const last = LEGEND_TICKS[LEGEND_TICKS.length - 1];
  const stops = [];
  for (let tick = first; tick <= last; tick += 5) {
    stops.push(`${colorForTemperature(tick)} ${legendTickPosition(tick).toFixed(2)}%`);
  }
  return `linear-gradient(90deg, ${stops.join(', ')})`;
}

// Badge number: rounded integer, ASCII hyphen-minus for negatives. The °C unit
// is drawn separately (regular weight, smaller) by the label layer.
function formatBadgeNumber(celsius) {
  return String(Math.round(celsius));
}

// Legend tick: integer with a real minus sign and a degree sign.
function formatLegendTick(celsius) {
  return `${celsius < 0 ? MINUS_SIGN : ''}${Math.abs(celsius)}\u00b0`;
}

// Popup figure: one decimal, real minus sign, degree Celsius; em dash when blank.
function formatTemperature(celsius) {
  if (celsius === null) return EM_DASH;
  const fixed = celsius.toFixed(1);
  return `${fixed === '-0.0' ? '0.0' : fixed.replace('-', MINUS_SIGN)} ${DEGREE_C}`;
}

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, character => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[character]));
}

// Deep link to the section that holds the chosen weather box. climateAnchor is
// a MediaWiki section id, so setting it through the URL API keeps any existing
// percent-escapes intact instead of double-encoding them. Without an anchor the
// link falls back to the article itself; without an article there is no link.
function climateSourceUrl(city) {
  if (!city || typeof city.wikipedia !== 'string' || city.wikipedia === '') return null;
  try {
    const url = new URL(city.wikipedia);
    if (city.climateAnchor) url.hash = city.climateAnchor;
    return url.href;
  } catch {
    return null;
  }
}

// Row labels are literals; only data values need escaping.
const POPUP_PRIMARY_ROWS = [
  ['High', 'meanDailyMax'],
  ['Average', 'dailyMean'],
  ['Low', 'meanDailyMin'],
];
const POPUP_EXTREME_ROWS = [
  ['Typical extreme high', 'meanMax'],
  ['Typical extreme low', 'meanMin'],
  ['Record high', 'recordHigh'],
  ['Record low', 'recordLow'],
];

function popupRowsHtml(rows, city, monthIndex) {
  return rows
    .map(([label, row]) => (
      `<div class="popup-row"><dt>${label}</dt>` +
      `<dd>${formatTemperature(monthValue(city, monthIndex, row))}</dd></div>`
    ))
    .join('');
}

function cityPopupHtml(city, monthIndex) {
  const sourceUrl = climateSourceUrl(city);
  return [
    '<div class="popup">',
    `<div class="popup-city">${escapeHtml(city.name || '')}</div>`,
    `<div class="popup-country">${escapeHtml(city.country || '')}</div>`,
    `<div class="popup-month">${MONTH_NAMES[monthIndex]}</div>`,
    `<dl class="popup-rows">${popupRowsHtml(POPUP_PRIMARY_ROWS, city, monthIndex)}</dl>`,
    `<dl class="popup-rows popup-rows-extras">${popupRowsHtml(POPUP_EXTREME_ROWS, city, monthIndex)}</dl>`,
    sourceUrl
      ? `<div class="popup-source">Source: <a href="${escapeHtml(sourceUrl)}" target="_blank" rel="noopener noreferrer">Wikipedia ${NORTH_EAST_ARROW}</a></div>`
      : '',
    '</div>',
  ].join('');
}

// One point per city carrying its label and the values clusters aggregate.
function buildFeatureCollection(cities, monthIndex, metricRow) {
  return {
    type: 'FeatureCollection',
    features: cities.map((city, index) => {
      const celsius = monthValue(city, monthIndex, metricRow);
      return {
        type: 'Feature',
        id: index,
        geometry: { type: 'Point', coordinates: [Number(city.lon), Number(city.lat)] },
        properties: {
          index,
          labelNumber: celsius === null ? EM_DASH : formatBadgeNumber(celsius),
          labelUnit: celsius === null ? '' : DEGREE_C,
          // Clusters aggregate these two (see the source's clusterProperties),
          // so the cluster layers can derive an average with one expression and
          // the same expressions also work for individual, unclustered points.
          sumCelsius: celsius === null ? 0 : celsius,
          dataCount: celsius === null ? 0 : 1,
        },
      };
    }),
  };
}

/* --------------------------------------------------------------------------
 * Application
 * ------------------------------------------------------------------------ */

function initApp() {
  const cities = getCityList();

  const slider = document.getElementById('month-slider');
  const monthNameElement = document.getElementById('month-name');
  const playButton = document.getElementById('play');
  const metricButtons = Array.from(document.querySelectorAll('.segmented button[data-metric]'));
  const bottomBar = document.querySelector('.bottombar');

  const map = new maplibregl.Map({
    container: 'map',
    center: [0, 20],
    zoom: 1,
    attributionControl: false, // replaced below by an always-expanded one
  });
  map.addControl(new maplibregl.NavigationControl(), 'top-right');
  // MapLibre collapses the credits into a button on maps narrower than 640 px;
  // compact:false keeps the OpenFreeMap / OpenMapTiles / OpenStreetMap line visible.
  map.addControl(new maplibregl.AttributionControl({ compact: false }));
  // Surface style/tile problems in the console instead of failing silently.
  map.on('error', event => {
    console.warn('[temperature-map] map error:', (event && event.error && event.error.message) || 'unknown');
  });
  applyMapStyle(map);

  let currentMonth = new Date().getMonth(); // the page opens on the current month
  let currentMetric = METRICS.find(metric => metric.id === DEFAULT_METRIC_ID);
  let styleReady = false;
  let isPlaying = false;
  let playTimer = null;
  let popup = null;
  let openCityIndex = null;

  function renderMonthChrome() {
    slider.value = String(currentMonth);
    monthNameElement.textContent = MONTH_NAMES[currentMonth];
  }

  function renderMetricChrome() {
    for (const button of metricButtons) {
      button.setAttribute('aria-pressed', String(button.dataset.metric === currentMetric.id));
    }
  }

  function refreshBadges() {
    if (!styleReady) return;
    map.getSource(DATA_SOURCE_ID).setData(buildFeatureCollection(cities, currentMonth, currentMetric.row));
  }

  function setMonth(nextMonth) {
    currentMonth = ((nextMonth % 12) + 12) % 12;
    renderMonthChrome();
    refreshBadges();
    refreshOpenPopup();
  }

  function setMetric(metricId) {
    const metric = METRICS.find(candidate => candidate.id === metricId);
    if (!metric || metric === currentMetric) return;
    setPlaying(false);
    currentMetric = metric;
    renderMetricChrome();
    refreshBadges();
    refreshOpenPopup();
  }

  function setPlaying(next) {
    isPlaying = next;
    playButton.setAttribute('aria-pressed', String(isPlaying));
    playButton.setAttribute('aria-label', isPlaying ? 'Pause month animation' : 'Play month animation');
    if (playTimer !== null) {
      clearInterval(playTimer);
      playTimer = null;
    }
    if (isPlaying) {
      playTimer = setInterval(() => setMonth(currentMonth + 1), PLAY_INTERVAL_MS);
    }
  }

  function refreshOpenPopup() {
    if (popup && openCityIndex !== null && cities[openCityIndex]) {
      popup.setHTML(cityPopupHtml(cities[openCityIndex], currentMonth));
    }
  }

  // A fresh popup per click: MapLibre snapshots its click listeners before
  // dispatching, so the previous popup's closeOnClick listener must belong to a
  // different instance or it would close the popup we just opened.
  function openCityPopup(index) {
    const city = cities[index];
    if (!city) return;
    if (popup) popup.remove(); // fires 'close' and clears the state below
    const next = new maplibregl.Popup({ maxWidth: '300px', offset: 12 });
    next.on('close', () => {
      if (popup === next) {
        popup = null;
        openCityIndex = null;
      }
    });
    popup = next;
    openCityIndex = index;
    next
      .setLngLat([Number(city.lon), Number(city.lat)])
      .setHTML(cityPopupHtml(city, currentMonth))
      .addTo(map);
  }

  // Dashed reference lines under the badges, plus labels placed along the
  // lines. The labels opt out of collision handling so they can never steal
  // placement from the cluster/city labels added afterwards (earlier symbol
  // layers win placement, so opting out is what keeps the badges in charge).
  function addReferenceLines() {
    map.addSource(REFERENCE_LINE_SOURCE_ID, {
      type: 'geojson',
      data: {
        type: 'FeatureCollection',
        features: REFERENCE_PARALLELS.map(({ name, latitude }) => ({
          type: 'Feature',
          properties: { name, latitude },
          geometry: { type: 'LineString', coordinates: [[-180, latitude], [180, latitude]] },
        })),
      },
    });

    map.addLayer({
      id: REFERENCE_LINE_LAYER_ID,
      type: 'line',
      source: REFERENCE_LINE_SOURCE_ID,
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#6b7280',
        'line-opacity': 0.7,
        'line-width': ['interpolate', ['linear'], ['zoom'], 0, 0.8, 4, 1.1, 8, 1.4],
        'line-dasharray': [1.5, 1.5],
      },
    });

    map.addLayer({
      id: REFERENCE_LABEL_LAYER_ID,
      type: 'symbol',
      source: REFERENCE_LINE_SOURCE_ID,
      layout: {
        'symbol-placement': 'line',
        'symbol-spacing': 700,
        'text-field': ['get', 'name'],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 0, 9, 5, 11],
        'text-letter-spacing': 0.12,
        'text-allow-overlap': true,
        'text-ignore-placement': true,
        'text-padding': 4,
      },
      paint: {
        'text-color': '#5b6478',
        'text-halo-color': 'rgba(255, 255, 255, 0.85)',
        'text-halo-width': 1,
      },
    });
  }

  function addBadgeLayers() {
    map.addSource(DATA_SOURCE_ID, {
      type: 'geojson',
      data: buildFeatureCollection(cities, currentMonth, currentMetric.row),
      // Overlapping badges merge into one circle showing the average of the
      // selected metric and the member count; clicking a cluster zooms to the
      // level where it splits.
      cluster: true,
      clusterRadius: CLUSTER_RADIUS,
      clusterMaxZoom: CLUSTER_MAX_ZOOM,
      clusterProperties: {
        sumCelsius: ['+', ['get', 'sumCelsius']],
        dataCount: ['+', ['get', 'dataCount']],
      },
    });

    // Average of the cluster's cities for the selected month/metric; singles
    // carry the same properties, so one set of expressions covers both.
    // Guarded division so an all-blank cluster can never produce NaN.
    const averageCelsius = ['case',
      ['==', ['get', 'dataCount'], 0], 0,
      ['/', ['get', 'sumCelsius'], ['get', 'dataCount']],
    ];
    const roundedAverage = ['floor', ['+', averageCelsius, 0.5]]; // = Math.round, without -0

    const circlePaint = () => ({
      'circle-color': ['case',
        ['==', ['get', 'dataCount'], 0], NO_DATA_COLOR,
        temperatureColorExpression(averageCelsius),
      ],
      'circle-stroke-color': '#ffffff',
      'circle-stroke-width': 0.8,
      'circle-opacity': 0.95,
    });

    // A zoom interpolation must be the top-level expression of a paint
    // property, so singles and clusters get one circle layer each.
    map.addLayer({
      id: CIRCLE_LAYER_ID,
      type: 'circle',
      source: DATA_SOURCE_ID,
      filter: ['!', ['has', 'point_count']],
      paint: {
        ...circlePaint(),
        // Sized for a comfortably padded bold label: roughly 19 px at zoom 3.4
        // growing to 26 px at zoom 6.
        'circle-radius': ['interpolate', ['linear'], ['zoom'], 3.4, 19, 6, 26],
      },
    });

    map.addLayer({
      id: CLUSTER_CIRCLE_LAYER_ID,
      type: 'circle',
      source: DATA_SOURCE_ID,
      filter: ['has', 'point_count'],
      paint: {
        ...circlePaint(),
        // Larger still, to fit the two-line label with the same colour padding.
        'circle-radius': ['interpolate', ['linear'], ['zoom'], 3.4, 22, 6, 29],
      },
    });

    // Wikipedia's own ink rule: white below -23.3 °C and from 37.8 °C up,
    // black in between. Deliberately no text halo: the crisp fill/text edge
    // reads better than a white glow around the glyphs.
    const badgeTextColor = ['case',
      ['<', averageCelsius, -23.3], LIGHT_TEXT_COLOR,
      ['>=', averageCelsius, 37.8], LIGHT_TEXT_COLOR,
      DARK_TEXT_COLOR,
    ];

    // Individual cities and clusters get separate symbol layers so each uses the
    // simplest possible expression (and either can be validated on its own).
    // Cluster labels are added first: MapLibre gives placement priority to
    // earlier symbol layers, so in dense areas the group average wins over the
    // individual labels it would otherwise be hidden behind.
    map.addLayer({
      id: CLUSTER_LABEL_LAYER_ID,
      type: 'symbol',
      source: DATA_SOURCE_ID,
      filter: ['has', 'point_count'],
      layout: {
        // Two lines inside the circle, e.g. "22°C" over "(2)": bold average with
        // the °C unit in the lighter regular face at full size; the count is the
        // same regular face, slightly smaller (0.8). 'format' must be the root
        // expression, so the blank case lives inside each section.
        'text-field': ['format',
          ['case',
            ['==', ['get', 'dataCount'], 0], EM_DASH,
            ['to-string', roundedAverage],
          ], { 'font-scale': 1, 'text-font': ['literal', ['Noto Sans Bold']] },
          ['case',
            ['==', ['get', 'dataCount'], 0], '',
            DEGREE_C,
          ], { 'font-scale': 1, 'text-font': ['literal', ['Noto Sans Regular']] },
          ['case',
            ['==', ['get', 'dataCount'], 0], '',
            ['concat', '\n(', ['to-string', ['get', 'point_count']], ')'],
          ], { 'font-scale': 0.8, 'text-font': ['literal', ['Noto Sans Regular']] },
        ],
        'text-font': ['Noto Sans Bold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 3.4, 12, 6, 16],
        'text-line-height': 1.05,
        'text-anchor': 'center',
        'text-allow-overlap': false,
        'text-ignore-placement': false,
      },
      paint: {
        'text-color': badgeTextColor,
      },
    });

    map.addLayer({
      id: LABEL_LAYER_ID,
      type: 'symbol',
      source: DATA_SOURCE_ID,
      filter: ['!', ['has', 'point_count']],
      layout: {
        // Bold number with the °C unit in the lighter regular face, full size.
        'text-field': ['format',
          ['get', 'labelNumber'], { 'font-scale': 1, 'text-font': ['literal', ['Noto Sans Bold']] },
          ['get', 'labelUnit'], { 'font-scale': 1, 'text-font': ['literal', ['Noto Sans Regular']] },
        ],
        'text-font': ['Noto Sans Bold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 3.4, 12, 6, 16],
        'text-anchor': 'center',
        // MapLibre's default collision handling: numbers that would overlap are
        // dropped adaptively while the circles underneath stay visible.
        'text-allow-overlap': false,
        'text-ignore-placement': false,
      },
      paint: {
        'text-color': badgeTextColor,
      },
    });

    function handleBadgeClick(event) {
      const feature = event.features && event.features[0];
      if (!feature) return;
      if (feature.properties && feature.properties.point_count) {
        // Cluster: zoom to the level where it breaks into its cities.
        map.getSource(DATA_SOURCE_ID)
          .getClusterExpansionZoom(feature.properties.cluster_id)
          .then(zoom => map.easeTo({ center: feature.geometry.coordinates, zoom }));
        return;
      }
      openCityPopup(Number(feature.properties.index));
    }

    for (const layerId of [CIRCLE_LAYER_ID, CLUSTER_CIRCLE_LAYER_ID, LABEL_LAYER_ID, CLUSTER_LABEL_LAYER_ID]) {
      map.on('click', layerId, handleBadgeClick);
      map.on('mouseenter', layerId, () => { map.getCanvas().style.cursor = 'pointer'; });
      map.on('mouseleave', layerId, () => { map.getCanvas().style.cursor = ''; });
    }
  }

  function fitToCities() {
    if (cities.length === 0) {
      map.jumpTo({ center: [0, 20], zoom: 1 });
      return;
    }
    const first = [Number(cities[0].lon), Number(cities[0].lat)];
    const bounds = cities.reduce(
      (box, city) => box.extend([Number(city.lon), Number(city.lat)]),
      new maplibregl.LngLatBounds(first, first),
    );
    map.fitBounds(bounds, {
      padding: { top: 80, right: 60, bottom: 110, left: 60 },
      maxZoom: 6,
      duration: 0,
    });
  }

  // Keep MapLibre's attribution above the bottom bar, whatever height it takes.
  function syncBottomBarHeight() {
    document.documentElement.style.setProperty('--bottombar-height', `${bottomBar.offsetHeight}px`);
  }

  function renderLegend() {
    document.getElementById('legend-gradient').style.background = legendGradientCss();
    document.getElementById('legend-ticks').append(...LEGEND_TICKS.map(tick => {
      const element = document.createElement('span');
      element.className = 'legend-tick';
      element.style.left = `${legendTickPosition(tick).toFixed(2)}%`;
      element.textContent = formatLegendTick(tick);
      return element;
    }));
  }

  function renderMonthTicks() {
    document.getElementById('month-ticks').append(...MONTH_SHORT.map(label => {
      const element = document.createElement('span');
      element.textContent = label;
      return element;
    }));
  }

  slider.addEventListener('input', () => {
    setPlaying(false); // manual scrubbing stops playback
    setMonth(Number(slider.value));
  });

  playButton.addEventListener('click', () => setPlaying(!isPlaying));

  for (const button of metricButtons) {
    button.addEventListener('click', () => setMetric(button.dataset.metric));
  }

  map.on('load', () => {
    styleReady = true;
    addReferenceLines();
    addBadgeLayers();
    fitToCities();
  });

  renderMonthChrome();
  renderMetricChrome();
  renderLegend();
  renderMonthTicks();
  setPlaying(false);
  new ResizeObserver(syncBottomBarHeight).observe(bottomBar);
  syncBottomBarHeight();
}

// index.html drives the app; the guard keeps the pure helpers importable/eval-able
// in Node for quick checks, e.g. `node -e "$(cat app.js)"`.
if (typeof document !== 'undefined') {
  initApp();
}
