/*
 * Europe Monthly Temperatures — map front-end.
 *
 * Plain ES2020 in one file, no build step: index.html is meant to be opened
 * straight from disk (file://). MapLibre GL JS v5 is the only external code and
 * is loaded from unpkg by index.html.
 *
 * Data comes from data/cities.js (generated by the scraper) when that file
 * exists, otherwise from mock/mock-cities.js, so the UI always has something to
 * draw. See getCityList().
 */

// OpenFreeMap `positron` — the one map style used, no API key required.
const MAP_STYLE_URL = 'https://tiles.openfreemap.org/styles/positron';

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];
const MONTH_SHORT = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

// The three selectable metrics: toggle label -> field of city.months.
const METRICS = [
  { id: 'high', label: 'High', row: 'meanDailyMax' },
  { id: 'average', label: 'Average', row: 'dailyMean' },
  { id: 'low', label: 'Low', row: 'meanDailyMin' },
];
const DEFAULT_METRIC_ID = 'average';

// Absolute colour scale, shared by every month and metric (RdBu): -25 °C and
// below is blue, 0 °C neutral, +40 °C and above red. Values outside the range
// clamp to the end colours.
const SCALE_MIN = -25;
const SCALE_MID = 0;
const SCALE_MAX = 40;
const COLOR_MIN = '#2166ac';
const COLOR_MID = '#f7f7f7';
const COLOR_MAX = '#b2182b';
const NO_DATA_COLOR = '#c9ced6';
const LIGHT_TEXT_COLOR = '#ffffff';
const DARK_TEXT_COLOR = '#14213d';

// Legend ticks, labelled in °C.
const LEGEND_TICKS = [-25, -10, 0, 10, 20, 30, 40];

const PLAY_INTERVAL_MS = 1500;

const MINUS_SIGN = '\u2212'; // real minus for popup figures; badges use ASCII '-'
const EM_DASH = '\u2014';
const DEGREE_C = '\u00b0C';

const DATA_SOURCE_ID = 'cities';
const CIRCLE_LAYER_ID = 'city-badges';
const LABEL_LAYER_ID = 'city-badge-labels';

/* --------------------------------------------------------------------------
 * Pure helpers
 * ------------------------------------------------------------------------ */

// data/cities.js wins when it loaded; mock/mock-cities.js is the fallback.
function getCityList() {
  const source = typeof CITY_DATA !== 'undefined' ? CITY_DATA : MOCK_CITY_DATA;
  const list = Array.isArray(source) ? source : (source && Array.isArray(source.cities) ? source.cities : []);
  return list.filter(isPlottableCity);
}

function isPlottableCity(city) {
  return Boolean(city) && Number.isFinite(Number(city.lat)) && Number.isFinite(Number(city.lon));
}

// Number for the given month/metric, or null when the row or the month is blank.
function monthValue(city, monthIndex, metricRow) {
  const series = city && city.months ? city.months[metricRow] : null;
  const value = Array.isArray(series) ? series[monthIndex] : null;
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

function hexToRgb(hex) {
  const value = parseInt(hex.slice(1), 16);
  return { r: (value >> 16) & 255, g: (value >> 8) & 255, b: value & 255 };
}

function mixRgb(from, to, amount) {
  const t = Math.min(1, Math.max(0, amount));
  return {
    r: from.r + (to.r - from.r) * t,
    g: from.g + (to.g - from.g) * t,
    b: from.b + (to.b - from.b) * t,
  };
}

function rgbToHex(rgb) {
  const channel = value => Math.round(value).toString(16).padStart(2, '0');
  return `#${channel(rgb.r)}${channel(rgb.g)}${channel(rgb.b)}`;
}

// Linear interpolation between the three scale anchors.
function colorForTemperature(celsius) {
  return celsius <= SCALE_MID
    ? rgbToHex(mixRgb(hexToRgb(COLOR_MIN), hexToRgb(COLOR_MID), (celsius - SCALE_MIN) / (SCALE_MID - SCALE_MIN)))
    : rgbToHex(mixRgb(hexToRgb(COLOR_MID), hexToRgb(COLOR_MAX), (celsius - SCALE_MID) / (SCALE_MAX - SCALE_MID)));
}

// sRGB relative luminance (WCAG).
function relativeLuminance(hex) {
  const { r, g, b } = hexToRgb(hex);
  const linearize = channel => {
    const s = channel / 255;
    return s <= 0.03928 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * linearize(r) + 0.7152 * linearize(g) + 0.0722 * linearize(b);
}

function contrastRatio(luminanceA, luminanceB) {
  const lighter = Math.max(luminanceA, luminanceB);
  const darker = Math.min(luminanceA, luminanceB);
  return (lighter + 0.05) / (darker + 0.05);
}

// The badge number is light or dark depending on which contrasts better with the fill.
function textColorForFill(fillHex) {
  const fill = relativeLuminance(fillHex);
  return contrastRatio(fill, relativeLuminance(LIGHT_TEXT_COLOR)) >=
    contrastRatio(fill, relativeLuminance(DARK_TEXT_COLOR))
    ? LIGHT_TEXT_COLOR
    : DARK_TEXT_COLOR;
}

function legendTickPosition(celsius) {
  const first = LEGEND_TICKS[0];
  const last = LEGEND_TICKS[LEGEND_TICKS.length - 1];
  return ((celsius - first) / (last - first)) * 100;
}

// Built from the same anchors as colorForTemperature, so the legend gradient
// matches the badges exactly.
function legendGradientCss() {
  const stops = LEGEND_TICKS.map(tick => `${colorForTemperature(tick)} ${legendTickPosition(tick).toFixed(2)}%`);
  return `linear-gradient(90deg, ${stops.join(', ')})`;
}

// Badge number: rounded integer, ASCII hyphen-minus for negatives.
function formatBadgeNumber(celsius) {
  return String(Math.round(celsius));
}

// Legend tick: integer with a real minus sign and a degree sign.
function formatLegendTick(celsius) {
  return `${celsius < 0 ? MINUS_SIGN : ''}${Math.abs(celsius)}\u00b0`;
}

// Popup figure: one decimal, real minus sign, degree Celsius; em dash when blank.
function formatTemperature(celsius) {
  if (celsius === null) return EM_DASH;
  const fixed = celsius.toFixed(1);
  return `${fixed === '-0.0' ? '0.0' : fixed.replace('-', MINUS_SIGN)} ${DEGREE_C}`;
}

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, character => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  }[character]));
}

// Row labels are literals; only data values need escaping.
const POPUP_PRIMARY_ROWS = [
  ['High', 'meanDailyMax'],
  ['Average', 'dailyMean'],
  ['Low', 'meanDailyMin'],
];
const POPUP_EXTREME_ROWS = [
  ['Typical extreme high', 'meanMax'],
  ['Typical extreme low', 'meanMin'],
  ['Record high', 'recordHigh'],
  ['Record low', 'recordLow'],
];

function popupRowsHtml(rows, city, monthIndex) {
  return rows
    .map(([label, row]) => (
      `<div class="popup-row"><dt>${label}</dt>` +
      `<dd>${formatTemperature(monthValue(city, monthIndex, row))}</dd></div>`
    ))
    .join('');
}

function cityPopupHtml(city, monthIndex) {
  return [
    '<div class="popup">',
    `<div class="popup-city">${escapeHtml(city.name || '')}</div>`,
    `<div class="popup-country">${escapeHtml(city.country || '')}</div>`,
    `<div class="popup-month">${MONTH_NAMES[monthIndex]}</div>`,
    `<dl class="popup-rows">${popupRowsHtml(POPUP_PRIMARY_ROWS, city, monthIndex)}</dl>`,
    `<dl class="popup-rows popup-rows-extras">${popupRowsHtml(POPUP_EXTREME_ROWS, city, monthIndex)}</dl>`,
    '</div>',
  ].join('');
}

// One point per city carrying the colour and label for the selected month/metric,
// so the circle and text layers stay simple `get` expressions.
function buildFeatureCollection(cities, monthIndex, metricRow) {
  return {
    type: 'FeatureCollection',
    features: cities.map((city, index) => {
      const celsius = monthValue(city, monthIndex, metricRow);
      const fill = celsius === null ? NO_DATA_COLOR : colorForTemperature(celsius);
      const textColor = textColorForFill(fill);
      return {
        type: 'Feature',
        id: index,
        geometry: { type: 'Point', coordinates: [Number(city.lon), Number(city.lat)] },
        properties: {
          index,
          fill,
          label: celsius === null ? EM_DASH : formatBadgeNumber(celsius),
          textColor,
          haloColor: textColor === LIGHT_TEXT_COLOR ? DARK_TEXT_COLOR : '#ffffff',
        },
      };
    }),
  };
}

/* --------------------------------------------------------------------------
 * Application
 * ------------------------------------------------------------------------ */

function initApp() {
  const cities = getCityList();

  const slider = document.getElementById('month-slider');
  const monthNameElement = document.getElementById('month-name');
  const playButton = document.getElementById('play');
  const metricButtons = Array.from(document.querySelectorAll('.segmented button[data-metric]'));
  const bottomBar = document.querySelector('.bottombar');

  const map = new maplibregl.Map({
    container: 'map',
    style: MAP_STYLE_URL,
    center: [12, 50],
    zoom: 3.5,
    attributionControl: false, // replaced below by an always-expanded one
  });
  map.addControl(new maplibregl.NavigationControl(), 'top-right');
  // MapLibre collapses the credits into a button on maps narrower than 640 px;
  // compact:false keeps the OpenFreeMap / OpenMapTiles / OpenStreetMap line visible.
  map.addControl(new maplibregl.AttributionControl({ compact: false }));

  let currentMonth = new Date().getMonth(); // the page opens on the current month
  let currentMetric = METRICS.find(metric => metric.id === DEFAULT_METRIC_ID);
  let styleReady = false;
  let isPlaying = false;
  let playTimer = null;
  let popup = null;
  let openCityIndex = null;

  function renderMonthChrome() {
    slider.value = String(currentMonth);
    monthNameElement.textContent = MONTH_NAMES[currentMonth];
  }

  function renderMetricChrome() {
    for (const button of metricButtons) {
      button.setAttribute('aria-pressed', String(button.dataset.metric === currentMetric.id));
    }
  }

  function refreshBadges() {
    if (!styleReady) return;
    map.getSource(DATA_SOURCE_ID).setData(buildFeatureCollection(cities, currentMonth, currentMetric.row));
  }

  function setMonth(nextMonth) {
    currentMonth = ((nextMonth % 12) + 12) % 12;
    renderMonthChrome();
    refreshBadges();
    refreshOpenPopup();
  }

  function setMetric(metricId) {
    const metric = METRICS.find(candidate => candidate.id === metricId);
    if (!metric || metric === currentMetric) return;
    setPlaying(false);
    currentMetric = metric;
    renderMetricChrome();
    refreshBadges();
    refreshOpenPopup();
  }

  function setPlaying(next) {
    isPlaying = next;
    playButton.setAttribute('aria-pressed', String(isPlaying));
    playButton.setAttribute('aria-label', isPlaying ? 'Pause month animation' : 'Play month animation');
    if (playTimer !== null) {
      clearInterval(playTimer);
      playTimer = null;
    }
    if (isPlaying) {
      playTimer = setInterval(() => setMonth(currentMonth + 1), PLAY_INTERVAL_MS);
    }
  }

  function refreshOpenPopup() {
    if (popup && openCityIndex !== null && cities[openCityIndex]) {
      popup.setHTML(cityPopupHtml(cities[openCityIndex], currentMonth));
    }
  }

  // A fresh popup per click: MapLibre snapshots its click listeners before
  // dispatching, so the previous popup's closeOnClick listener must belong to a
  // different instance or it would close the popup we just opened.
  function openCityPopup(index) {
    const city = cities[index];
    if (!city) return;
    if (popup) popup.remove(); // fires 'close' and clears the state below
    const next = new maplibregl.Popup({ maxWidth: '300px', offset: 12 });
    next.on('close', () => {
      if (popup === next) {
        popup = null;
        openCityIndex = null;
      }
    });
    popup = next;
    openCityIndex = index;
    next
      .setLngLat([Number(city.lon), Number(city.lat)])
      .setHTML(cityPopupHtml(city, currentMonth))
      .addTo(map);
  }

  function addBadgeLayers() {
    map.addSource(DATA_SOURCE_ID, {
      type: 'geojson',
      data: buildFeatureCollection(cities, currentMonth, currentMetric.row),
    });

    map.addLayer({
      id: CIRCLE_LAYER_ID,
      type: 'circle',
      source: DATA_SOURCE_ID,
      paint: {
        'circle-color': ['get', 'fill'],
        // Roughly 8 px at zoom 3.4 growing to 12 px at zoom 6.
        'circle-radius': ['interpolate', ['linear'], ['zoom'], 3.4, 8, 6, 12],
        'circle-stroke-color': '#ffffff',
        'circle-stroke-width': 1.2,
        'circle-opacity': 0.95,
      },
    });

    map.addLayer({
      id: LABEL_LAYER_ID,
      type: 'symbol',
      source: DATA_SOURCE_ID,
      layout: {
        'text-field': ['get', 'label'],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 3.4, 10, 6, 12],
        'text-anchor': 'center',
        // MapLibre's default collision handling: numbers that would overlap are
        // dropped adaptively while the circles underneath stay visible.
        'text-allow-overlap': false,
        'text-ignore-placement': false,
      },
      paint: {
        'text-color': ['get', 'textColor'],
        'text-halo-color': ['get', 'haloColor'],
        'text-halo-width': 1.2,
      },
    });

    for (const layerId of [CIRCLE_LAYER_ID, LABEL_LAYER_ID]) {
      map.on('click', layerId, event => {
        const feature = event.features && event.features[0];
        if (feature) openCityPopup(Number(feature.properties.index));
      });
      map.on('mouseenter', layerId, () => { map.getCanvas().style.cursor = 'pointer'; });
      map.on('mouseleave', layerId, () => { map.getCanvas().style.cursor = ''; });
    }
  }

  function fitToCities() {
    if (cities.length === 0) {
      map.jumpTo({ center: [12, 50], zoom: 3.5 });
      return;
    }
    const first = [Number(cities[0].lon), Number(cities[0].lat)];
    const bounds = cities.reduce(
      (box, city) => box.extend([Number(city.lon), Number(city.lat)]),
      new maplibregl.LngLatBounds(first, first),
    );
    map.fitBounds(bounds, {
      padding: { top: 80, right: 60, bottom: 110, left: 60 },
      maxZoom: 6,
      duration: 0,
    });
  }

  // Keep MapLibre's attribution above the bottom bar, whatever height it takes.
  function syncBottomBarHeight() {
    document.documentElement.style.setProperty('--bottombar-height', `${bottomBar.offsetHeight}px`);
  }

  function renderLegend() {
    document.getElementById('legend-gradient').style.background = legendGradientCss();
    document.getElementById('legend-ticks').append(...LEGEND_TICKS.map(tick => {
      const element = document.createElement('span');
      element.className = 'legend-tick';
      element.style.left = `${legendTickPosition(tick).toFixed(2)}%`;
      element.textContent = formatLegendTick(tick);
      return element;
    }));
  }

  function renderMonthTicks() {
    document.getElementById('month-ticks').append(...MONTH_SHORT.map(label => {
      const element = document.createElement('span');
      element.textContent = label;
      return element;
    }));
  }

  slider.addEventListener('input', () => {
    setPlaying(false); // manual scrubbing stops playback
    setMonth(Number(slider.value));
  });

  playButton.addEventListener('click', () => setPlaying(!isPlaying));

  for (const button of metricButtons) {
    button.addEventListener('click', () => setMetric(button.dataset.metric));
  }

  map.on('load', () => {
    styleReady = true;
    addBadgeLayers();
    fitToCities();
  });

  renderMonthChrome();
  renderMetricChrome();
  renderLegend();
  renderMonthTicks();
  setPlaying(false);
  new ResizeObserver(syncBottomBarHeight).observe(bottomBar);
  syncBottomBarHeight();
}

// index.html drives the app; the guard keeps the pure helpers importable/eval-able
// in Node for quick checks, e.g. `node -e "$(cat app.js)"`.
if (typeof document !== 'undefined') {
  initApp();
}
