// Curated list of national capitals of European sovereign states, keyed by the
// English Wikipedia article title of the capital. Cross-checked against
// "List of sovereign states and dependent territories in Europe".
//
// Transcontinental states (Russia, Turkey, Georgia, Armenia, Azerbaijan,
// Kazakhstan) are included; Kazakhstan was explicitly approved by the
// supervisor. Kosovo is included even though Wikipedia's sovereign-states table
// omits it. The Netherlands uses Amsterdam (capital); The Hague is not included.
export const CAPITALS = [
  { name: 'Tirana', article: 'Tirana', country: 'Albania' },
  { name: 'Andorra la Vella', article: 'Andorra la Vella', country: 'Andorra' },
  { name: 'Yerevan', article: 'Yerevan', country: 'Armenia' },
  { name: 'Vienna', article: 'Vienna', country: 'Austria' },
  { name: 'Baku', article: 'Baku', country: 'Azerbaijan' },
  { name: 'Minsk', article: 'Minsk', country: 'Belarus' },
  { name: 'Brussels', article: 'Brussels', country: 'Belgium' },
  { name: 'Sarajevo', article: 'Sarajevo', country: 'Bosnia and Herzegovina' },
  { name: 'Sofia', article: 'Sofia', country: 'Bulgaria' },
  { name: 'Zagreb', article: 'Zagreb', country: 'Croatia' },
  { name: 'Nicosia', article: 'Nicosia', country: 'Cyprus' },
  { name: 'Prague', article: 'Prague', country: 'Czech Republic' },
  { name: 'Copenhagen', article: 'Copenhagen', country: 'Denmark' },
  { name: 'Tallinn', article: 'Tallinn', country: 'Estonia' },
  { name: 'Helsinki', article: 'Helsinki', country: 'Finland' },
  { name: 'Paris', article: 'Paris', country: 'France' },
  { name: 'Tbilisi', article: 'Tbilisi', country: 'Georgia' },
  { name: 'Berlin', article: 'Berlin', country: 'Germany' },
  { name: 'Athens', article: 'Athens', country: 'Greece' },
  { name: 'Budapest', article: 'Budapest', country: 'Hungary' },
  { name: 'Reykjavík', article: 'Reykjavík', country: 'Iceland' },
  { name: 'Dublin', article: 'Dublin', country: 'Ireland' },
  { name: 'Rome', article: 'Rome', country: 'Italy' },
  { name: 'Astana', article: 'Astana', country: 'Kazakhstan' },
  { name: 'Pristina', article: 'Pristina', country: 'Kosovo' },
  { name: 'Riga', article: 'Riga', country: 'Latvia' },
  { name: 'Vaduz', article: 'Vaduz', country: 'Liechtenstein' },
  { name: 'Vilnius', article: 'Vilnius', country: 'Lithuania' },
  { name: 'Luxembourg', article: 'Luxembourg (city)', country: 'Luxembourg' },
  { name: 'Valletta', article: 'Valletta', country: 'Malta' },
  { name: 'Chișinău', article: 'Chișinău', country: 'Moldova' },
  { name: 'Monaco', article: 'Monaco', country: 'Monaco' },
  { name: 'Podgorica', article: 'Podgorica', country: 'Montenegro' },
  { name: 'Amsterdam', article: 'Amsterdam', country: 'Netherlands' },
  { name: 'Skopje', article: 'Skopje', country: 'North Macedonia' },
  { name: 'Oslo', article: 'Oslo', country: 'Norway' },
  { name: 'Warsaw', article: 'Warsaw', country: 'Poland' },
  { name: 'Lisbon', article: 'Lisbon', country: 'Portugal' },
  { name: 'Bucharest', article: 'Bucharest', country: 'Romania' },
  { name: 'Moscow', article: 'Moscow', country: 'Russia' },
  { name: 'City of San Marino', article: 'City of San Marino', country: 'San Marino' },
  { name: 'Belgrade', article: 'Belgrade', country: 'Serbia' },
  { name: 'Bratislava', article: 'Bratislava', country: 'Slovakia' },
  { name: 'Ljubljana', article: 'Ljubljana', country: 'Slovenia' },
  { name: 'Madrid', article: 'Madrid', country: 'Spain' },
  { name: 'Stockholm', article: 'Stockholm', country: 'Sweden' },
  { name: 'Bern', article: 'Bern', country: 'Switzerland' },
  { name: 'Ankara', article: 'Ankara', country: 'Turkey' },
  { name: 'Kyiv', article: 'Kyiv', country: 'Ukraine' },
  { name: 'London', article: 'London', country: 'United Kingdom' },
  { name: 'Vatican City', article: 'Vatican City', country: 'Vatican City' },
];
