// Curated list of national capitals, keyed by the English Wikipedia article
// title of the capital. Drafted from Wikidata (P36 capital of current sovereign
// states, historical states excluded) and cross-checked against Wikipedia's
// "List of national capitals"; Rawalpindi removed (P36 error), St. John's added
// by hand, Brussels points at "Brussels" rather than "City of Brussels" (the
// municipality article carries no weather box). Capitals bypass the population
// threshold but still have to carry a
// weather box to survive the merge (see withExtraCities).
//
// Countries with more than one official/administrative capital list each city:
// South Africa (Pretoria, Cape Town, Bloemfontein), Sri Lanka (Sri Jayawardenepura
// Kotte, Colombo), Bolivia (Sucre, La Paz), Eswatini (Mbabane, Lobamba), Yemen
// (Sanaa, Aden) and Palestine (Ramallah, East Jerusalem).
export const CAPITALS = [
  { name: "Abu Dhabi", article: "Abu Dhabi", country: "United Arab Emirates" },
  { name: "Abuja", article: "Abuja", country: "Nigeria" },
  { name: "Accra", article: "Accra", country: "Ghana" },
  { name: "Addis Ababa", article: "Addis Ababa", country: "Ethiopia" },
  { name: "Aden", article: "Aden", country: "Yemen" },
  { name: "Algiers", article: "Algiers", country: "Algeria" },
  { name: "Amman", article: "Amman", country: "Jordan" },
  { name: "Amsterdam", article: "Amsterdam", country: "Kingdom of the Netherlands" },
  { name: "Andorra la Vella", article: "Andorra la Vella", country: "Andorra" },
  { name: "Ankara", article: "Ankara", country: "Turkey" },
  { name: "Antananarivo", article: "Antananarivo", country: "Madagascar" },
  { name: "Apia", article: "Apia", country: "Samoa" },
  { name: "Ashgabat", article: "Ashgabat", country: "Turkmenistan" },
  { name: "Asmara", article: "Asmara", country: "Eritrea" },
  { name: "Astana", article: "Astana", country: "Kazakhstan" },
  { name: "Asunción", article: "Asunción", country: "Paraguay" },
  { name: "Athens", article: "Athens", country: "Greece" },
  { name: "Baghdad", article: "Baghdad", country: "Iraq" },
  { name: "Baku", article: "Baku", country: "Azerbaijan" },
  { name: "Bamako", article: "Bamako", country: "Mali" },
  { name: "Bandar Seri Begawan", article: "Bandar Seri Begawan", country: "Brunei" },
  { name: "Bangkok", article: "Bangkok", country: "Thailand" },
  { name: "Bangui", article: "Bangui", country: "Central African Republic" },
  { name: "Banjul", article: "Banjul", country: "The Gambia" },
  { name: "Basseterre", article: "Basseterre", country: "Saint Kitts and Nevis" },
  { name: "Beijing", article: "Beijing", country: "People's Republic of China" },
  { name: "Beirut", article: "Beirut", country: "Lebanon" },
  { name: "Belgrade", article: "Belgrade", country: "Serbia" },
  { name: "Belmopan", article: "Belmopan", country: "Belize" },
  { name: "Berlin", article: "Berlin", country: "Germany" },
  { name: "Bern", article: "Bern", country: "Switzerland" },
  { name: "Bishkek", article: "Bishkek", country: "Kyrgyzstan" },
  { name: "Bissau", article: "Bissau", country: "Guinea-Bissau" },
  { name: "Bloemfontein", article: "Bloemfontein", country: "South Africa" },
  { name: "Bogotá", article: "Bogotá", country: "Colombia" },
  { name: "Brasília", article: "Brasília", country: "Brazil" },
  { name: "Bratislava", article: "Bratislava", country: "Slovakia" },
  { name: "Brazzaville", article: "Brazzaville", country: "Republic of the Congo" },
  { name: "Bridgetown", article: "Bridgetown", country: "Barbados" },
  { name: "Brussels", article: "Brussels", country: "Belgium" },
  { name: "Bucharest", article: "Bucharest", country: "Romania" },
  { name: "Budapest", article: "Budapest", country: "Hungary" },
  { name: "Buenos Aires", article: "Buenos Aires", country: "Argentina" },
  { name: "Cairo", article: "Cairo", country: "Egypt" },
  { name: "Canberra", article: "Canberra", country: "Australia" },
  { name: "Cape Town", article: "Cape Town", country: "South Africa" },
  { name: "Caracas", article: "Caracas", country: "Venezuela" },
  { name: "Castries", article: "Castries", country: "Saint Lucia" },
  { name: "Chișinău", article: "Chișinău", country: "Moldova" },
  { name: "Ciudad de la Paz", article: "Ciudad de la Paz", country: "Equatorial Guinea" },
  { name: "Colombo", article: "Colombo", country: "Sri Lanka" },
  { name: "Conakry", article: "Conakry", country: "Guinea" },
  { name: "Copenhagen", article: "Copenhagen", country: "Kingdom of Denmark" },
  { name: "Dakar", article: "Dakar", country: "Senegal" },
  { name: "Damascus", article: "Damascus", country: "Syria" },
  { name: "Dhaka", article: "Dhaka", country: "Bangladesh" },
  { name: "Dili", article: "Dili", country: "Timor-Leste" },
  { name: "Djibouti", article: "Djibouti City", country: "Djibouti" },
  { name: "Dodoma", article: "Dodoma", country: "Tanzania" },
  { name: "Doha", article: "Doha", country: "Qatar" },
  { name: "Dublin", article: "Dublin", country: "Ireland" },
  { name: "Dushanbe", article: "Dushanbe", country: "Tajikistan" },
  { name: "East Jerusalem", article: "East Jerusalem", country: "Palestine" },
  { name: "Freetown", article: "Freetown", country: "Sierra Leone" },
  { name: "Funafuti", article: "Funafuti", country: "Tuvalu" },
  { name: "Gaborone", article: "Gaborone", country: "Botswana" },
  { name: "Georgetown", article: "Georgetown, Guyana", country: "Guyana" },
  { name: "Gitega", article: "Gitega", country: "Burundi" },
  { name: "Guatemala City", article: "Guatemala City", country: "Guatemala" },
  { name: "Hanoi", article: "Hanoi", country: "Vietnam" },
  { name: "Harare", article: "Harare", country: "Zimbabwe" },
  { name: "Havana", article: "Havana", country: "Cuba" },
  { name: "Helsinki", article: "Helsinki", country: "Finland" },
  { name: "Honiara", article: "Honiara", country: "Solomon Islands" },
  { name: "Islamabad", article: "Islamabad", country: "Pakistan" },
  { name: "Jakarta", article: "Jakarta", country: "Indonesia" },
  { name: "Jerusalem", article: "Jerusalem", country: "Israel" },
  { name: "Juba", article: "Juba", country: "South Sudan" },
  { name: "Kabul", article: "Kabul", country: "Afghanistan" },
  { name: "Kampala", article: "Kampala", country: "Uganda" },
  { name: "Kathmandu", article: "Kathmandu", country: "Nepal" },
  { name: "Khartoum", article: "Khartoum", country: "Sudan" },
  { name: "Kigali", article: "Kigali", country: "Rwanda" },
  { name: "Kingston", article: "Kingston, Jamaica", country: "Jamaica" },
  { name: "Kingstown", article: "Kingstown", country: "Saint Vincent and the Grenadines" },
  { name: "Kinshasa", article: "Kinshasa", country: "Democratic Republic of the Congo" },
  { name: "Kuala Lumpur", article: "Kuala Lumpur", country: "Malaysia" },
  { name: "Kuwait City", article: "Kuwait City", country: "Kuwait" },
  { name: "Kyiv", article: "Kyiv", country: "Ukraine" },
  { name: "La Paz", article: "La Paz", country: "Bolivia" },
  { name: "Libreville", article: "Libreville", country: "Gabon" },
  { name: "Lilongwe", article: "Lilongwe", country: "Malawi" },
  { name: "Lima", article: "Lima", country: "Peru" },
  { name: "Lisbon", article: "Lisbon", country: "Portugal" },
  { name: "Ljubljana", article: "Ljubljana", country: "Slovenia" },
  { name: "Lobamba", article: "Lobamba", country: "Eswatini" },
  { name: "Lomé", article: "Lomé", country: "Togo" },
  { name: "London", article: "London", country: "United Kingdom" },
  { name: "Luanda", article: "Luanda", country: "Angola" },
  { name: "Lusaka", article: "Lusaka", country: "Zambia" },
  { name: "Luxembourg", article: "Luxembourg City", country: "Luxembourg" },
  { name: "Madrid", article: "Madrid", country: "Spain" },
  { name: "Majuro", article: "Majuro", country: "Marshall Islands" },
  { name: "Malé", article: "Malé", country: "Maldives" },
  { name: "Managua", article: "Managua", country: "Nicaragua" },
  { name: "Manama", article: "Manama", country: "Bahrain" },
  { name: "Manila", article: "Manila", country: "Philippines" },
  { name: "Maputo", article: "Maputo", country: "Mozambique" },
  { name: "Maseru", article: "Maseru", country: "Lesotho" },
  { name: "Mbabane", article: "Mbabane", country: "Eswatini" },
  { name: "Mexico City", article: "Mexico City", country: "Mexico" },
  { name: "Minsk", article: "Minsk", country: "Belarus" },
  { name: "Mogadishu", article: "Mogadishu", country: "Somalia" },
  { name: "Monaco", article: "Monaco", country: "Monaco" },
  { name: "Monrovia", article: "Monrovia", country: "Liberia" },
  { name: "Montevideo", article: "Montevideo", country: "Uruguay" },
  { name: "Moroni", article: "Moroni, Comoros", country: "Comoros" },
  { name: "Moscow", article: "Moscow", country: "Russia" },
  { name: "Muscat", article: "Muscat", country: "Oman" },
  { name: "N'Djamena", article: "N'Djamena", country: "Chad" },
  { name: "Nairobi", article: "Nairobi", country: "Kenya" },
  { name: "Nassau", article: "Nassau, Bahamas", country: "The Bahamas" },
  { name: "Naypyidaw", article: "Naypyidaw", country: "Myanmar" },
  { name: "New Delhi", article: "New Delhi", country: "India" },
  { name: "Ngerulmud", article: "Ngerulmud", country: "Palau" },
  { name: "Niamey", article: "Niamey", country: "Niger" },
  { name: "Nicosia", article: "Nicosia", country: "Cyprus" },
  { name: "Nouakchott", article: "Nouakchott", country: "Mauritania" },
  { name: "Nukuʻalofa", article: "Nukuʻalofa", country: "Tonga" },
  { name: "Oslo", article: "Oslo", country: "Norway" },
  { name: "Ottawa", article: "Ottawa", country: "Canada" },
  { name: "Ouagadougou", article: "Ouagadougou", country: "Burkina Faso" },
  { name: "Palikir", article: "Palikir", country: "Federated States of Micronesia" },
  { name: "Panama City", article: "Panama City", country: "Panama" },
  { name: "Paramaribo", article: "Paramaribo", country: "Suriname" },
  { name: "Paris", article: "Paris", country: "France" },
  { name: "Phnom Penh", article: "Phnom Penh", country: "Cambodia" },
  { name: "Podgorica", article: "Podgorica", country: "Montenegro" },
  { name: "Port Louis", article: "Port Louis", country: "Mauritius" },
  { name: "Port Moresby", article: "Port Moresby", country: "Papua New Guinea" },
  { name: "Port of Spain", article: "Port of Spain", country: "Trinidad and Tobago" },
  { name: "Port Vila", article: "Port Vila", country: "Vanuatu" },
  { name: "Port-au-Prince", article: "Port-au-Prince", country: "Haiti" },
  { name: "Porto-Novo", article: "Porto-Novo", country: "Benin" },
  { name: "Prague", article: "Prague", country: "Czech Republic" },
  { name: "Praia", article: "Praia", country: "Cape Verde" },
  { name: "Pretoria", article: "Pretoria", country: "South Africa" },
  { name: "Pristina", article: "Pristina", country: "Kosovo" },
  { name: "Pyongyang", article: "Pyongyang", country: "North Korea" },
  { name: "Quito", article: "Quito", country: "Ecuador" },
  { name: "Rabat", article: "Rabat", country: "Morocco" },
  { name: "Ramallah", article: "Ramallah", country: "Palestine" },
  { name: "Reykjavík", article: "Reykjavík", country: "Iceland" },
  { name: "Riga", article: "Riga", country: "Latvia" },
  { name: "Riyadh", article: "Riyadh", country: "Saudi Arabia" },
  { name: "Rome", article: "Rome", country: "Italy" },
  { name: "Roseau", article: "Roseau", country: "Dominica" },
  { name: "San José", article: "San José, Costa Rica", country: "Costa Rica" },
  { name: "San Marino", article: "City of San Marino", country: "San Marino" },
  { name: "San Salvador", article: "San Salvador", country: "El Salvador" },
  { name: "Sanaa", article: "Sanaa", country: "Yemen" },
  { name: "Santiago", article: "Santiago", country: "Chile" },
  { name: "Santo Domingo", article: "Santo Domingo", country: "Dominican Republic" },
  { name: "São Tomé", article: "São Tomé", country: "São Tomé and Príncipe" },
  { name: "Sarajevo", article: "Sarajevo", country: "Bosnia and Herzegovina" },
  { name: "Seoul", article: "Seoul", country: "South Korea" },
  { name: "Singapore", article: "Singapore", country: "Singapore" },
  { name: "Skopje", article: "Skopje", country: "North Macedonia" },
  { name: "Sofia", article: "Sofia", country: "Bulgaria" },
  { name: "South Tarawa", article: "South Tarawa", country: "Kiribati" },
  { name: "Sri Jayawardenepura Kotte", article: "Sri Jayawardenepura Kotte", country: "Sri Lanka" },
  { name: "St. George's", article: "St. George's, Grenada", country: "Grenada" },
  { name: "St. John's", article: "St. John's, Antigua and Barbuda", country: "Antigua and Barbuda" },
  { name: "Stockholm", article: "Stockholm", country: "Sweden" },
  { name: "Sucre", article: "Sucre", country: "Bolivia" },
  { name: "Suva", article: "Suva", country: "Fiji" },
  { name: "Taipei", article: "Taipei", country: "Taiwan" },
  { name: "Tallinn", article: "Tallinn", country: "Estonia" },
  { name: "Tashkent", article: "Tashkent", country: "Uzbekistan" },
  { name: "Tbilisi", article: "Tbilisi", country: "Georgia" },
  { name: "Tegucigalpa", article: "Tegucigalpa", country: "Honduras" },
  { name: "Tehran", article: "Tehran", country: "Iran" },
  { name: "Thimphu", article: "Thimphu", country: "Bhutan" },
  { name: "Tirana", article: "Tirana", country: "Albania" },
  { name: "Tokyo", article: "Tokyo", country: "Japan" },
  { name: "Tripoli", article: "Tripoli, Libya", country: "Libya" },
  { name: "Tunis", article: "Tunis", country: "Tunisia" },
  { name: "Ulaanbaatar", article: "Ulaanbaatar", country: "Mongolia" },
  { name: "Vaduz", article: "Vaduz", country: "Liechtenstein" },
  { name: "Valletta", article: "Valletta", country: "Malta" },
  { name: "Vatican City", article: "Vatican City", country: "Vatican City" },
  { name: "Victoria", article: "Victoria, Seychelles", country: "Seychelles" },
  { name: "Vienna", article: "Vienna", country: "Austria" },
  { name: "Vientiane", article: "Vientiane", country: "Laos" },
  { name: "Vilnius", article: "Vilnius", country: "Lithuania" },
  { name: "Warsaw", article: "Warsaw", country: "Poland" },
  { name: "Washington, D.C.", article: "Washington, D.C.", country: "United States" },
  { name: "Wellington", article: "Wellington", country: "New Zealand" },
  { name: "Windhoek", article: "Windhoek", country: "Namibia" },
  { name: "Yamoussoukro", article: "Yamoussoukro", country: "Ivory Coast" },
  { name: "Yaoundé", article: "Yaoundé", country: "Cameroon" },
  { name: "Yaren", article: "Yaren", country: "Nauru" },
  { name: "Yerevan", article: "Yerevan", country: "Armenia" },
  { name: "Zagreb", article: "Zagreb", country: "Croatia" },
];
